spring:
  application:
    name: aiService
  data:
    mongodb:
      uri: mongodb+srv://aryan24bcs10305_db_user:VIMUu1HjAzKFWTxm@cluster0.xlblsq2.mongodb.net/fitnessrecommendation?appName=Cluster0
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8083